version: "2"
run:
  go: 1.24.7
linters:
  enable:
    - forbidigo
    - funlen
    - gocyclo
    - gosec
    - lll
    - misspell
    - nilerr
    - nlreturn
    - nolintlint
    - revive
    - staticcheck
    - unparam
    - whitespace
    - wsl_v5
  settings:
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print(|f|ln)$
        - pattern: ^spew\.Dump$
    funlen:
      lines: 260
      statements: 88
    gocyclo:
      min-complexity: 67
    lll:
      line-length: 150
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
    wsl:
      allow-cuddle-declarations: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/coretrix/hitrix)
    goimports:
      local-prefixes:
        - github.com/coretrix/hitrix
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
